### ISSUE TITLE
关于数据集划分和结果统计问题

### ISSUE THREAD

**Issue by LinpengPan** [NUIST-Videocoding/VCRNet#3]
作者你好，在论文中提到，您在训练过程中是按照7：2：1的比例划分训练集、测试集和验证集的，但是代码里面确实按照8：2的比例划分训练集和测试集的，并且论文中提到 您汇报的是10次划分的均值，但是您代码里面给出的结果是10次划分的中值，请问为什么会出现不一致的情况？

**Comment by NUIST-Videocoding** [comment]
您好，感谢您的提醒。我刚才check了一遍代码，确实存在您所说的问题，应该是当时为了测不同超参下的性能结果编写了多个文件副本，在上传代码时出现了错误。目前我们已将您说的问题进行了修正，感谢您的关注！
